// Auto-generated from Category_Item_Supplier_UOM.xlsx
export interface StoreItemMaster {
  item: string;
  category: string;
  uom: string;
  suppliers: string[];
}

export const STORE_ITEM_MASTER: StoreItemMaster[] = [
  { item: '2PCS CASHEW', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['NUTRIA FOODS'] },
  { item: 'AASHIRVAD ATTA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'AJWAIN', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'AMONIA', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'AMUL FRESH CREAM', category: 'PRIMARY_OUTLET', uom: 'Nos', suppliers: ['KRISHNA ENTERPRISES'] },
  { item: 'ANJURA(dry fig) ATHIPALAM', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'APPALAM 200 GMS', category: 'PRIMARY_OUTLET', uom: 'PKT', suppliers: ['MK SPICES'] },
  { item: 'AROMATIC MIX', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'ASAFOETIDA PASTE', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: [] },
  { item: 'ASAFOETIDA POWDER', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['SS PANDIAN & SONS'] },
  { item: 'AVALAKKAI RED BULK', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: [] },
  { item: 'AVALAKKI', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['NEB'] },
  { item: 'BADAM', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'BADAM MIX POWDER 500gms jar', category: 'PRIMARY_OUTLET', uom: 'nos', suppliers: ['MK SPICES'] },
  { item: 'BAJJI MIX MASALA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'BAKING POWDER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'BEST RICE FLOUR', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['GEETHA STOTE'] },
  { item: 'BIRIYANI LEAFS', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: [] },
  { item: 'BIRIYANI MASALA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'BLACK SALT', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'BLACK TILL', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'BOOST', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: [] },
  { item: 'BOURN VITA', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'BREAD CRUMBS 1 KG', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'BREAD IMPROVER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'BROWN SUGAR', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['JA VEE YES'] },
  { item: 'BURA SUGAR', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'BUTTER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['JA VEE YES'] },
  { item: 'BUTTER PAPER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'BYADAGI CHILLI', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: [] },
  { item: 'CALCIUM CORPONATE', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: [] },
  { item: 'CARAMEL', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'CHANA DAL BROWN', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'CHANA MASALA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'CHANNA DAL (P K P)', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'CHAT MASALA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'CHERRY', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'CHHOLE MASSLA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'CHIA SEEDS', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: [] },
  { item: 'CHICKEN MASALA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'CHILLY POWDER', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'CHOCO NUTS', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'CHOCO NUTS ( WHITE )', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'CHOCOLATE SILVER LEAVES', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'CLASSIC EGGFREE CHOCOLATE MIX (celebration)', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'COCO POWDER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'COCONUT', category: 'PRIMARY_OUTLET', uom: 'Pcs', suppliers: ['SRI VENKATESHWARA'] },
  { item: 'COCONUT POWDER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'COCONUT SEEVEL', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'COLOR BALLS', category: 'PRIMARY_OUTLET', uom: 'PKT', suppliers: ['MK SPICES'] },
  { item: 'CORIANDER POWDER', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'CORIANDER SEEDS', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'CORN CHIP', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: [] },
  { item: 'CORN FLOUR', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'CRYSTAL SALT', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['SHIVAMANI AGENCIES'] },
  { item: 'CUMIN', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'CUMIN POWDER', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'CURRY MASALA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'CUSTERD POWDER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'DARK BAR', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'DATES SEEDS', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'DOSA RAVA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['SRINIVASA AGENCIES'] },
  { item: 'DRY CHILLY', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['apooji'] },
  { item: 'DRY COCONUT', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['SRI VENKATESHWARA'] },
  { item: 'DRY GINGER POWDER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'DRY GRAPES', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'DRY MANGO POwdER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'EGG', category: 'PRIMARY_OUTLET', uom: 'Nos', suppliers: ['PANDIYAN EGGS'] },
  { item: 'EGGLESS CHOCOLATE PRE MIX', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'EGGLESS MAYONESS', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'EGGLESS RED VELVET CAKE MIX', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: [] },
  { item: 'EGGLESS VENNILA POWDER MIX', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'ELACHI POWDER', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: [] },
  { item: 'ELACHI SEEDS', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'EXEL GLUTON', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'FANCY BALLS', category: 'PRIMARY_OUTLET', uom: 'PKT', suppliers: ['MK SPICES'] },
  { item: 'FONDANT / SUGAR PASTE black', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'FONDANT / SUGAR PASTE red', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'FONDANT / SUGAR PASTE pink', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'FOOD GEL TOWER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'FRESH CREAM WAPER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'FRIED GRAM FLOUR', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['OTHERS'] },
  { item: 'GLUCOSE POWDER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: [] },
  { item: 'GRAM MASALA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'GREEN MOONG DAL', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'GREEN PEAS (RAW)', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'GROUNTNUT', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['apooji'] },
  { item: 'GROUNTNUT 2 PCS', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['IYYANGAR BAKEREY'] },
  { item: 'HONEY 1 LTR', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: [] },
  { item: 'HORLICKS', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['SSS AGENCY'] },
  { item: 'ICING SUGAR', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'IDLY RAVA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['SRINIVASA AGENCIES'] },
  { item: 'JAGGERY', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['SARASWATHY UNPOLISHED GRAINS'] },
  { item: 'JALJEER POW', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'JATHIPATHRI', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: [] },
  { item: 'JAVARISI', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'KABAB STICK 12 INCH', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'KABULI CHANA DAL (WHITE)', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'KALAKANTH TRAY', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['GUNAVATHY COVA'] },
  { item: 'KASHMIRI CHILLI MASALA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'KASTHURI METHI', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'KEWRA WATER (500 ML)', category: 'PRIMARY_OUTLET', uom: 'Nos', suppliers: ['MK SPICES'] },
  { item: 'KICHEN KING MASALA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'LAVANGAM', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'LEMON SALT', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'LIQ GLUCOSE', category: 'PRIMARY_OUTLET', uom: 'Ltrs', suppliers: ['OTHERS'] },
  { item: 'LOLIPOP STICK', category: 'PRIMARY_OUTLET', uom: 'PKT', suppliers: [] },
  { item: 'MAIDA', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['RAGAVENDRA TRADERS'] },
  { item: 'MANA THAKKALI VATHAL', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: [] },
  { item: 'MANGO BAR', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'MATKI', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: [] },
  { item: 'MILK MAID 0.335', category: 'PRIMARY_OUTLET', uom: 'NOS', suppliers: ['SRINIVASA AGENCIES'] },
  { item: 'MILK POWDER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['JA VEE YES'] },
  { item: 'Mixed Friuty', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'MIXED JAM', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'MOONG DAL', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['apooji'] },
  { item: 'MUSTERD', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'MUTTAN MASALA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'MYSOOR DAL', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['apooji'] },
  { item: 'NOODLES', category: 'PRIMARY_OUTLET', uom: 'PKT', suppliers: ['MK SPICES'] },
  { item: 'NUTMEG POWDER', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: [] },
  { item: 'NUTMEG SEEDS', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'OATS (QUAKER)', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'OATS (SAFFOLA)', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'ORANGE BAR', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'PAANI POORI MASALA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'PALM JAGGERY', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: [] },
  { item: 'PAPER AVALAKKI', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: [] },
  { item: 'PASTA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'PATTA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'PAV BHAJI MASALA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'PEPPER', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'PEPPER POWDER', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: [] },
  { item: 'PINEAPPLE BAR', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'PISTA', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'PISTA BAR', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'POPPY SEED', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'PUFFED RICE ( UNSLAT )', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['NEB'] },
  { item: 'PULIYODHIRAI MASALA', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'RAGI', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['NEB'] },
  { item: 'RAGI FLOUR', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['NEB'] },
  { item: 'RAJMA', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: [] },
  { item: 'RASAM POWDER', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'RICHS WHIP TOPPING GOLD fresh cream', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'ROASTED RAVA', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['JA VEE YES CO'] },
  { item: 'SABJA SEED', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'SAFRAN POWDER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'SALT', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['SHIVAMANI AGENCIES'] },
  { item: 'SAMBA WHEAT SEEDS', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'SAMBAR POWDER', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'SEMIYA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: [] },
  { item: 'SHANKAR GRAM FLOUR', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['apooji'] },
  { item: 'SILVER BALLS', category: 'PRIMARY_OUTLET', uom: 'PKT', suppliers: ['MK SPICES'] },
  { item: 'New Surya CHILLY POWDER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: [] },
  { item: 'New Surya CURRY MASALA', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'SODA', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'SOMP (FENNEL)', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'SOMP POWDER (FENNEL)', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: [] },
  { item: 'Soya Beans', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['NEB'] },
  { item: 'SPECIAL STICK (BURGER)', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'SPL CASHEW ( W240 )', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['NUTRIA FOODS'] },
  { item: 'SPL FRIED GRAM', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['OTHERS'] },
  { item: 'SQUARE JAGGRY CAUVERY', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: [] },
  { item: 'STRAWBERRY BAR', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'SUGAR', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['apooji'] },
  { item: 'SUNDA VATHAL', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['UNIVERSAL VENDORS'] },
  { item: 'SWEET BALLS', category: 'PRIMARY_OUTLET', uom: 'PKT', suppliers: ['MK SPICES'] },
  { item: 'SWEET COVA (KALAKANDHU)', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['GUNAVATHY'] },
  { item: 'SWEETLESS COVA', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['GUNAVATHY COVA'] },
  { item: 'TAMRIND', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'TILL (NYLON GINGILY)', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'TIN CHERRY', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'TOOR DAL', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['NEB'] },
  { item: 'TOOTH PICK', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['OTHERS'] },
  { item: 'TOWER JEL', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'TURMURIC POWDER', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'UPAD RAVA', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['RAGAVENDRA TRADERS'] },
  { item: 'URAD DAL', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['JA VEE YES'] },
  { item: 'VENDHAYAM ( FENUGREEK )', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'VENNILA POWDER', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'VIJAY RICE FLOUR', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['apooji'] },
  { item: 'VINEGAR', category: 'PRIMARY_OUTLET', uom: 'Lts', suppliers: ['MK SPICES'] },
  { item: 'WALNUT USA', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'WATERMELON SEED', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['DRY FRUIT SHOP BERIGAI'] },
  { item: 'WHITE BALLS', category: 'PRIMARY_OUTLET', uom: 'PKT', suppliers: ['MK SPICES'] },
  { item: 'WHITE BAR', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'WHITE PEPPER', category: 'PRIMARY_OUTLET', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'WHITE TILL', category: 'PRIMARY_OUTLET', uom: 'Nos', suppliers: ['SRI RAM REDDY'] },
  { item: 'WAFER BISCUIT PARLE', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['JA VEE YES'] },
  { item: 'YEAST', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['JA VEE YES'] },
  { item: 'SUNFLOWER SEED GRAIN BRO', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['JA VEE YES', 'SARASWATHY'] },
  { item: 'BASMATHI RICE CLASSIC', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['NEB', 'AKSHITHA ENTERPRISES'] },
  { item: 'TAJMAHAL RICE', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['NEB'] },
  { item: 'BULLET RICE', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['NEB'] },
  { item: 'IDLY RICE', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['NEW SURYA HOUSE', 'NEB'] },
  { item: 'NANDHINI GHEE', category: 'PRIMARY_OUTLET', uom: 'LTR', suppliers: ['GOLDEN FARIMART', 'JA VEE YAE'] },
  { item: 'JVS REF OIL', category: 'PRIMARY_OUTLET', uom: 'LTR', suppliers: ['JA VEE YES CO', 'JA VEE YAE'] },
  { item: 'PALM OIL', category: 'PRIMARY_OUTLET', uom: 'LTR', suppliers: ['JA VEE YES CO', 'JA VEE YAE'] },
  { item: 'SUNDROP OIL', category: 'PRIMARY_OUTLET', uom: 'LTR', suppliers: ['JA VEE YAE'] },
  { item: 'BAKERKING DALTA', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['JA VEE YES CO'] },
  { item: 'BISCUITS DALTA MARVO PRIDE)', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['JA VEE YES CO'] },
  { item: 'CREAM DALTA(MARVO EXCEL)', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['JA VEE YES CO'] },
  { item: 'GSM DALDA', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['JA VEE YES CO'] },
  { item: 'PUFFS DALTA(LILLY LITE)', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['JA VE SE'] },
  { item: 'SUPREME DALTA', category: 'PRIMARY_OUTLET', uom: 'Kgs', suppliers: ['JA VE SE'] },
  { item: 'JVS GROUNDNUT OIL', category: 'PRIMARY_OUTLET', uom: 'LTR', suppliers: ['JA VEE YAE'] },
  { item: 'MUSTUARD OIL', category: 'PRIMARY_OUTLET', uom: 'LTR', suppliers: ['JA VEE YES CO', 'JA VEE YAE'] },
  { item: 'DEEPAM OIL', category: 'PRIMARY_OUTLET', uom: 'LTR', suppliers: ['JA VEE YAE'] },
  { item: 'GINGELLY OIL', category: 'PRIMARY_OUTLET', uom: 'LTR', suppliers: ['AKSHITHA ENTERPRISES', 'JA VEE YAE'] },
  { item: 'COCONUT OIL', category: 'PRIMARY_OUTLET', uom: 'LTR', suppliers: ['AKSHITHA ENTERPRISES'] },
  { item: '1 Kg Nonwoven Bags', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'TEA CUP', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['DD'] },
  { item: '( BC 0 ) Without Print', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '1.5kg Cake Base', category: 'PACKING MATRLS', uom: 'NOS', suppliers: [] },
  { item: '1.5kg Cake Base Round', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '1.5kg Cake Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '1000CC Snacks Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH'] },
  { item: '100G Cover', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '100G Zipper Pouch', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '10pcs Cake Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '1500CC Snacks Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH'] },
  { item: '16x20 Tray Cover', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['ANEESH'] },
  { item: '18x24 Tray Cover', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['ANEESH'] },
  { item: '1kg Cake Base', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '1kg Cake Base ( Round )', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '1kg Cake Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '1Kg Folding Box Mett', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '1Kg Reg Sweet box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '1Kg Silver Mould', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '1Kg PRIMARY_OUTLET Paper Bag', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '1Kg Spl Cake Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '1Kg Spl Sweet box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '20*26 TRAY COVER', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '200Gms Cake Mould Paper', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '200ML PET Bottle ( BADAM&ROSE MILK )', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH'] },
  { item: '100ML PET  Bottle', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH BHAI'] },
  { item: '110ML PET Bottle', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH BHAI'] },
  { item: '20x30 Tray Cover', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '250CC Snacks Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH'] },
  { item: '250G Window Pouch', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '250G Zipper Pouch', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '250gms Reg Sweet box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '250Gms PRIMARY_OUTLET Paper Bag', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '250Gms Spl Sweet Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '250Gms Spl Sweet Box (Top)', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '250ML Bottle ( Chutney Powder )', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '2kg Cake Base', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '2kg Cake Base ( Round )', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '2kg Cake Box 12.12.4', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['MK SPICES'] },
  { item: '2Pcs Cake Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '2Pcs Cake FC Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '33x25 STICKER ROLL (CORE 1"&5000 NOS)', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['SSR SOLUTIONS'] },
  { item: '350ML ( Cake jar )', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '375CC Snacks Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '3Kg Cake Base', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '3Kg Cake Base Round', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '3kg Cake Box 15.15.5', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['MK SPICES'] },
  { item: '3x3 Cover', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '4kg Cake Base', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '4kg Cake Box 16.20', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['MK SPICES'] },
  { item: '4pcs Cake Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '4Pcs Cake FC Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '4x4 Cover', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '4x5 Cover', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '500CC Snacks Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH'] },
  { item: '500gms Cake Base', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '500gms Cake Base Round', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '500gms Cake Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '500Gms Cake Mould  Paper', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '500GMS FC CAKE BOX', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '500Gms Reg Sweet Box  PLAIN BLACK', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH'] },
  { item: '500gms PRIMARY_OUTLET Paper bag', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '500gms Spl Sweet box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '50G Window Pouch', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '5Kg Cake Base', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '5Kg Cake Base Round', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '5kg Cake Box 20*25', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['MK SPICES'] },
  { item: '5KG Nonwoven Bags', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '5X5 Cover PP', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['ANEESH BHAI'] },
  { item: '5x6 Cover PP', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '6pcs Cake Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '6x7 cover PP', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['ANEESH BHAI'] },
  { item: '6X9 Cover PP', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['ANEESH BHAI'] },
  { item: '5X8 Cover PP', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['ANEESH BAY'] },
  { item: '5X7 Cover PP', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['ANEESH BAY'] },
  { item: '3X4 Cover PP', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['ANEESH BAY'] },
  { item: '9x15 Hand Cover', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '9X4 Envelope', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Andhra Muruku Zipper Pouch', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'Avalakki Sticker', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'ROUND Basket', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH'] },
  { item: 'Basket 3', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Basket 4', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Bc(1) Unprint', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'Bill Roll', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ESAA'] },
  { item: 'BIO BAGS - 13*16', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['ANEESH BHAI'] },
  { item: 'BIO BAGS 10*13', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'Birthday Knife', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['MK SPICES'] },
  { item: 'Black Plate Platter', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Bombay Mixture Zipper Pouch', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'Cake Order Book', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Chettinadu Muruku Zipper Pouch', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'DLX Plastic Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Extra Large PRIMARY_OUTLET Paper Bag', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Fruit Cake Packing Cover', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'Garbage cover SMALL', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['MK SPICES'] },
  { item: 'GARBAGE COVER (48*60) EX LONG', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['ANEESH'] },
  { item: 'Gift Box 1kg', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Gift Box 500Gms', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Gift laadu Box Big', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Gift Laadu Box Small', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Gold Round Cup (RASAMALAI)', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Hand Cloth', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH'] },
  { item: 'Hand Glouse', category: 'PACKING MATRLS', uom: 'PKT', suppliers: [] },
  { item: 'HEAD CAP', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH'] },
  { item: 'Kara Boondhi Zipper Pouch', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'Laadu Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Laadu jar', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'LD Silky ( 0 40 ) 500GMS', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['ANEESH'] },
  { item: 'Mangalore Mixture Zipper Pouch', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'Masala Pori Zipper Pouch', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'PIZZA BOX 9*9', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH'] },
  { item: 'MASALA DOSA BOX', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH'] },
  { item: 'Muffin Cup Cake Paper (laddu cup)', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Mullu Murukku Zipper Pouch', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'NET BASKET ( 8*8)', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'NET BASKET (6*6)', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH'] },
  { item: 'Paper Bandel', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'Paper Cup Laadu', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'Paper Cup Square', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Paper Plate', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH'] },
  { item: 'Paper PLATE 12"', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH BHAI'] },
  { item: 'Gift Boxes SINGLE PIECE (100 GMS)', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH BHAI'] },
  { item: 'Plate Cover ( 13x13 Sheet )', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'Preesing Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'PRESSING BOX 1000', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'PRESSING BOX 1500', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Round Gift Packing  Small', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Round Gift Packing Big', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Rubber', category: 'PACKING MATRLS', uom: 'PKT', suppliers: ['ANEESH BHAI'] },
  { item: 'ALUMINIUM foil (silver foil)', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH BHAI'] },
  { item: 'SALSA JAR GOLDENCAP', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Sandwich box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '100ML ROUND BOX', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'New Surya 16x20 bio cover', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['ANEESH BHAI'] },
  { item: 'New Surya 250gms Silver Cover', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'New Surya 7X11 ( BC 0 ) STRAIGHT', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['SS POLYMERS'] },
  { item: 'New Surya 8X15 ( BC 1 )', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['SS POLYMERS'] },
  { item: 'New Surya 9×15', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'New Surya Bread Cover GREEN', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'New Surya Bread Cover', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'New Surya Cortan Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'New Surya Jamoon Box', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'New Surya Large Cloth Bag', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['S TEX TRADING'] },
  { item: 'New Surya Large White Bag', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'New Surya Oats Cookies', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'New Surya Small Cloth Bag', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: ['S TEX TRADING'] },
  { item: 'New Surya Special Mixture Zipper Pouch', category: 'PACKING MATRLS', uom: 'Ltrs', suppliers: [] },
  { item: 'New Surya TAPE ROLL', category: 'PACKING MATRLS', uom: 'Lts', suppliers: [] },
  { item: 'SPORK SPOON WOODEN', category: 'PACKING MATRLS', uom: 'PKT', suppliers: ['ANEESH BHAI'] },
  { item: 'SQUARE 500ML BOX PLAIN', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH'] },
  { item: 'SQUARE 750', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'SQUARE BOX 1000ML', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'SQUARE BOX 500ML', category: 'PACKING MATRLS', uom: 'NOS', suppliers: ['ANEESH'] },
  { item: 'Standy Zipper Pouch (1Kg)', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'Sun Wrap Roll (2 KGS)', category: 'PACKING MATRLS', uom: 'NOS', suppliers: ['ANEESH BHAI'] },
  { item: 'Thenkuzhal Murukku Masala Zipper Pouch', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'Thenkuzhal Murukku Zipper Pouch', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'Till Murukku Zipper Pouch', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: 'Tissue Paper', category: 'PACKING MATRLS', uom: 'PKT', suppliers: [] },
  { item: 'Tissue Paper PRIMARY_OUTLET', category: 'PACKING MATRLS', uom: 'PKT', suppliers: [] },
  { item: 'JUICE CUP', category: 'PACKING MATRLS', uom: 'PKT', suppliers: ['DD SUPER MARKET'] },
  { item: 'Wax Ribbon (110X300MTR)', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'WOODEN SPOON', category: 'PACKING MATRLS', uom: 'PKT', suppliers: ['ANEESH'] },
  { item: 'Yellow Gift Boxes', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'Zipper Pouch ( 180X45x230)', category: 'PACKING MATRLS', uom: 'Kgs', suppliers: [] },
  { item: '1INCH TAPE DISPENSER', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '3INCH TAPE DISPENSER', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '500 ML ROUND BOX', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '7.7  CAKE BASE SQUARE (500G)', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: '9.9 BASE 1KG CAKE', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'B/H CORN BOWL', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'CARRTON BOX', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'CAKE ORDER FORM', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['CKV ENTERPRISES'] },
  { item: 'ALUMINIUM POUCH (1/2 LTR TEA PARCEL)', category: 'PACKING MATRLS', uom: 'Nos', suppliers: ['ANEESH BHAI'] },
  { item: 'BARBIE DOLL', category: 'PACKING MATRLS', uom: 'Nos', suppliers: [] },
  { item: 'TAPE 3 INCH 130MTRS', category: 'PACKING MATRLS', uom: 'NOS', suppliers: ['ANEESH'] },
  { item: 'New Surya COTTON BOX SLEEVE RED', category: 'PACKING MATRLS', uom: 'NOS', suppliers: ['GUPTA PRINTERS SIVAKASI'] },
  { item: 'New Surya COTTON BOX SLEEVE GREEN', category: 'PACKING MATRLS', uom: 'NOS', suppliers: ['GUPTA PRINTERS'] },
  { item: 'New Surya COTTON BOX SLEEVE PURPPLE', category: 'PACKING MATRLS', uom: 'NOS', suppliers: ['GUPTA PRINTERS'] },
  { item: 'New Surya COTTON BOX SLEEVE ORANGE', category: 'PACKING MATRLS', uom: 'NOS', suppliers: ['GUPTA PRINTERS'] },
  { item: 'BROOM STICK', category: 'CLEANING', uom: 'NOS', suppliers: [] },
  { item: 'DETIOL', category: 'CLEANING', uom: 'LTR', suppliers: [] },
  { item: 'FLOOR MOP', category: 'CLEANING', uom: 'NOS', suppliers: [] },
  { item: 'FLOOR WIPER', category: 'CLEANING', uom: 'NOS', suppliers: [] },
  { item: 'HAND WASH', category: 'CLEANING', uom: 'LTR', suppliers: ['NRB AGENCY'] },
  { item: 'HIT COCOKROACHES', category: 'CLEANING', uom: 'NOS', suppliers: [] },
  { item: 'LIZOL', category: 'CLEANING', uom: 'LTR', suppliers: [] },
  { item: 'PHENYL', category: 'CLEANING', uom: 'LTR', suppliers: ['NRB AGENCY'] },
  { item: 'PLASTIC FLOOR WIPER', category: 'CLEANING', uom: 'NOS', suppliers: [] },
  { item: 'RIN', category: 'CLEANING', uom: 'NOS', suppliers: [] },
  { item: 'RIN BAR', category: 'CLEANING', uom: 'NOS', suppliers: [] },
  { item: 'RIN POWDER 500 gms', category: 'CLEANING', uom: 'pkt', suppliers: ['SSS AGENCY WHOLESALE'] },
  { item: 'SURF EXCEL POWDER 500 gms', category: 'CLEANING', uom: 'pkt', suppliers: ['SSS AGENCY WHOLESALE'] },
  { item: 'SOAP POWDER', category: 'CLEANING', uom: 'KGS', suppliers: [] },
  { item: 'STEEL SCRUBER', category: 'CLEANING', uom: 'NOS', suppliers: [] },
  { item: 'TOILET BRUSH', category: 'CLEANING', uom: 'NOS', suppliers: [] },
  { item: 'VIM SCRUB', category: 'CLEANING', uom: 'NOS', suppliers: [] },
  { item: 'VIM SOAP', category: 'CLEANING', uom: 'NOS', suppliers: ['SSS AGENCY WHOLESALE'] },
  { item: 'VIM SOAP OIL', category: 'CLEANING', uom: 'LTR', suppliers: [] },
  { item: 'FLAX SEED GRAIN BRO', category: 'GRAIN BRO', uom: 'KG', suppliers: ['SARASWATHY'] },
  { item: 'FRIED GRAM GRAIN BRO', category: 'GRAIN BRO', uom: 'KG', suppliers: ['SARASWATHY'] },
  { item: 'GROUNTNUT GRAIN BRO', category: 'GRAIN BRO', uom: 'KG', suppliers: ['SARASWATHY'] },
  { item: 'GROUNTNUT 5 LTR GRAIN BRO', category: 'GRAIN BRO', uom: 'KG', suppliers: ['SARASWATHY'] },
  { item: 'JAGGERY GRAIN BRO', category: 'GRAIN BRO', uom: 'KG', suppliers: ['SARASWATHY'] },
  { item: 'GROUNTNUT OIL GRAIN BRO', category: 'GRAIN BRO', uom: 'LTR', suppliers: ['SARASWATHY'] },
  { item: 'PUMPKIN SEED GRAIN BRO', category: 'GRAIN BRO', uom: 'KG', suppliers: ['SARASWATHY'] },
  { item: 'SESAME SEED GRAIN BRO', category: 'GRAIN BRO', uom: 'KG', suppliers: ['SARASWATHY'] },
  { item: 'GREEN MOONG DAL GRAIN BRO', category: 'GRAIN BRO', uom: 'KGS', suppliers: ['SARASWATHY'] },
  { item: 'URAD DAL  GRAIN BRO', category: 'GRAIN BRO', uom: 'KGS', suppliers: ['SARASWATHY'] },
  { item: 'VARAGU (KODO) FLOUR GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'PEARL MILLET GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'GREAT MILLET JOWER FLOUR', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'KARUPPU KAVUNI RICE GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'RED RICE GAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'RAGI GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'MILLET HEALTH MIX GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'BROWNTOP MILLET GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'JOLA GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'IDLY RICE GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'RAJAMUDI RICE GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'QUINOA  GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'AMLA STUFF GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'AMLA CANDY GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'GROUNTNUT CHUTENY POWDER GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'FLAX SEED  CHUTENY POWDER GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'NIGAR SEED  CHUTENY POWDER GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'RAGI FLOUR GRAIN BRO', category: 'GRAIN BRO', uom: 'Kgs', suppliers: ['SARASWATHY'] },
  { item: 'LITTLE MILLET (SAMAI)', category: 'GRAIN BRO', uom: 'KG', suppliers: ['SARASWATHY'] },
  { item: 'FOXTAIL MILLET (THINAI)', category: 'GRAIN BRO', uom: 'KG', suppliers: ['SARASWATHY'] },
  { item: 'BARYARD MILLET GRAIN BRO', category: 'GRAIN BRO', uom: 'KG', suppliers: ['SARASWATHY'] },
  { item: 'CHIA SEED GRAIN BRO', category: 'GRAIN BRO', uom: 'KG', suppliers: ['SARASWATHY'] },
  { item: 'COCONUT OIL GRAIN BRO', category: 'GRAIN BRO', uom: 'LTR', suppliers: ['SARASWATHY'] },
  { item: 'GROUNDNUT OIL', category: 'GHEE', uom: 'LTR', suppliers: ['JA VEE YAE'] },
  { item: 'CURD', category: 'VEG & FRUITS', uom: 'LTR', suppliers: ['MANJUNATHA MILK'] },
  { item: 'MILK', category: 'VEG & FRUITS', uom: 'LTR', suppliers: ['MILK Dairy'] },
  { item: 'COW MILK', category: 'VEG & FRUITS', uom: 'LTR', suppliers: ['MILK DIARY'] },
  { item: 'COFFEE POWDER', category: 'VEG & FRUITS', uom: 'KGS', suppliers: [] },
  { item: 'TEA POWDER', category: 'VEG & FRUITS', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'BEANS', category: 'VEG & FRUITS', uom: 'kgs', suppliers: ['MURALI MARKET'] },
  { item: 'CARROT', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'CAPSICUM', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'CABBAGE', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'GREEN CHILLY', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'CAULIFLOWER', category: 'VEG & FRUITS', uom: 'PCS', suppliers: ['MURALI MARKET'] },
  { item: 'MINT LEAVES ( PUDINA )', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'CORIANDER LEAVES', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'CURRY LEAVES', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'CUCUMBER', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'PALAK LEAVES', category: 'VEG & FRUITS', uom: 'KAT', suppliers: ['MURALI MARKET'] },
  { item: 'VENDHYA KEERAI(METHI KURA)', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'RIDGE GOURD( Peerkangai)', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'MULLANGI(RADISH)', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'TOMATO', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'DRUMSTICK', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'BRINJAL', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'LEMON', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'BEETROOT', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'BITTER GOURD', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'BOTTLE GOURD', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'LADIES FINGER', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'PUMPKIN', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'WHITE PUMPKIN', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['UNIVERSAL VENDORS'] },
  { item: 'GREEN PEAS (AVARAI)', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'SMALL ONION', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MANJU ONION'] },
  { item: 'POTATO', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MANJU ONION'] },
  { item: 'POTATO CHIPS', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MANJU ONION'] },
  { item: 'ONION', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MANJU ONION'] },
  { item: 'GARLIC', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MANJU ONION'] },
  { item: 'GINGER', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MANJU ONION'] },
  { item: 'BAJJI BANANA', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'BANANA', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'RAW BANANA chips', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'BAJJI chilly', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'KUCHIKILANGU', category: 'VEG & FRUITS', uom: 'KG', suppliers: [] },
  { item: 'MILKYMIST CHEDDER CHEESE 1KG', category: 'VEG & FRUITS', uom: 'KGS', suppliers: ['MK SPICES'] },
  { item: 'CHEESE SLICE 765 GMS', category: 'VEG & FRUITS', uom: 'NOS', suppliers: ['MK SPICES'] },
  { item: 'CHEESE BLOCK 1 KG', category: 'VEG & FRUITS', uom: 'PKT', suppliers: ['MK SPICES'] },
  { item: 'FRENCH FRIES 6 mm', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MK SPICES'] },
  { item: 'VEG BURGER PATTY 1.2 KG', category: 'VEG & FRUITS', uom: 'PKT', suppliers: ['MK SPICES'] },
  { item: 'BANANA LEAF TIFFEN', category: 'VEG & FRUITS', uom: 'NOS', suppliers: ['KAMATCHI LEAF MUNDY'] },
  { item: 'BANANALEAF LUNCH', category: 'VEG & FRUITS', uom: 'NOS', suppliers: ['SRI KAMATCHICHI'] },
  { item: 'PANNEER', category: 'VEG & FRUITS', uom: 'KGS', suppliers: ['SK ENTERPRISES'] },
  { item: 'MUSHROOM', category: 'VEG & FRUITS', uom: 'PKT', suppliers: ['MURALI MARKET'] },
  { item: 'BABY CORN', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['SK ENTERPRISES'] },
  { item: 'SWEET CORN', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['SK ENTERPRISES'] },
  { item: 'GREEN PEAS (FROZEN) 1 KG', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MK SPICES'] },
  { item: 'WATER BOTTLE 1000 ML', category: 'VEG & FRUITS', uom: 'NOS', suppliers: ['MYURA'] },
  { item: 'WATER BOTTLE 500 ML', category: 'VEG & FRUITS', uom: 'NOS', suppliers: ['AKSHITHA ENTERPRISES'] },
  { item: 'WATER BOTTLE 300 ML', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['GOLDEN FARIMART'] },
  { item: 'APPLE', category: 'VEG & FRUITS', uom: 'KGS', suppliers: ['UNIVERSAL VENDORS'] },
  { item: 'GRAPES(GREEN)', category: 'VEG & FRUITS', uom: 'KG', suppliers: [] },
  { item: 'PAPAYA', category: 'VEG & FRUITS', uom: 'KG', suppliers: [] },
  { item: 'GONGORU', category: 'VEG & FRUITS', uom: 'KAT', suppliers: ['MURALI MARKET'] },
  { item: 'JACK FRUIT', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['SRI KAMATCHICHI'] },
  { item: 'MANGO', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['UNIVERSAL VENDORS'] },
  { item: 'PINEAPPLE', category: 'VEG & FRUITS', uom: 'KG', suppliers: ['MURALI MARKET'] },
  { item: 'ORANGE', category: 'VEG & FRUITS', uom: 'KGS', suppliers: ['UNIVERSAL VENDORS'] },
  { item: 'POMOGRANATE', category: 'VEG & FRUITS', uom: 'KGS', suppliers: ['UNIVERSAL VENDORS'] },
  { item: 'FANTA', category: 'VEG & FRUITS', uom: 'NOS', suppliers: ['MYURA'] },
  { item: 'COMBO VANILLA + STRAWBERRY 750ML (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'Combo Vanilla + Butterscotch 750Ml (Ice Cream)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'Combo Vanilla + Mango 750 Ml (Ice Cream)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'Combo Vanilla + Arabian Delight 750Ml (Ice Cream)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'Crunchy Cone Strawberry * 12 (Ice Cream)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'Crunchy Cone Butterscotch * 12 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'Exotic Roasted Almond 100 Ml * 6 (Ice Cream)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'EXOTIC ARABIAN DELIGHT 100ML*6', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'EXOTIC BELGIUM DREAM 100ML*6', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'EXOTIC FIG & HONEY 100ML*6', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'EXOTIC BLACK CURRENT 100 ML * 6 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'EXOTIC JACKFRUIT 100ML * 6 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'EXOTIC TENDER COCONUT 100ML * 6 (Ice Cream)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'Family Red Velvet 500 Ml (Ice Cream)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'Family Avacoda 500 Ml (Ice Cream)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'Family Vanilla 500 Ml (Ice Cream)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'Family Strawberry 500Ml (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'FAMILY RICH CHOCOLATE 500 ML (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'FAMILY BUTTERSCOTCH 500ML (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'FAMILY PISTA CHIO 500 ML (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'RED VELVET DREAM 750 ML (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'MAGIC FUNDOO PINEAPPLE *6 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'MAGIC FUNDOO MANGO *6 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'MAGIC FUNDOO ORANGE *6 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'MAGIC FUNDOO COMBO 100 ML *3', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'MAGIC POP', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'ROYAL CONE BUTTERSCOTCH*12 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'ROYAL CONE BLACK CURRENT*12 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'ROYAL CONE VANILA 120*12 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'ROYAL CONE ARABIAN DELIGHT*12 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'ROYAL CONE DELIGHT SPANISH * 12 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'ROYAL CONE CHOCOLATE 120 * 12 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'ROYAL CASSATA 100ML * 6 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'PREMIUM SICK CHOCOBAR * 20 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'PREMIUM STICK WHITE CHOCOBAR * 20 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'PREMIUM STICK MANGO DUET * 20 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'PREMIUM STICK NUTTYBAR POUCH*20(ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'PREMIUM STICK ALMONT KULFI *20 (ICE CREAM )', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'PARTY VANILLA 1000ML(ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'PARTY PISTA Chio1000ml (Ice Cream)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'PARTY RICH CHOCOLATE 1000ML (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'PARTY ALPHONSO MANGO 1000ML (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'PARTY STRAWBERRY 1000ML (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'MUTKA KULFI * 6 (ICE CREAM)', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'CUP BUTTERSCOTCH 70ML*18', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'CUP PISTA 70ML*18', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'PUTTU ICECREAM 600ML', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'MANGO BALL * 12', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'STRAWBERRY BALL * 12', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'KIWI BALL VANILA * 20', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'FUN TREAT CHOCO RIPPLE*6', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'FUN TREAT PISTA*6', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'FUN TREAT STRAWBERRY *6', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'FRUIT SUNDAE 100 ML *8', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'FUN TREAT VANILA*6', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'CUP VANILLA 50 ML *24', category: 'ICECREAM', uom: 'NOS', suppliers: ['cool magic agencies'] },
  { item: 'BANANA ESS', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ESS BANANA BUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ESS BUTTERSCOTCH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ESS CHOCOLATE', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ESS ICE CREAM', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ESS MANGO', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ESS MILK', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ESS SWEET ORANGE', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ESS PINAPPLE', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ESS PISTA', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ESS ROSE MALAS ROSE SYRUB', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ESS Rose White', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ESS SAFFRON', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ESS VANILLA', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'LEMON ESS', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'MIXED FURITS ESS', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ORANGE ESS BUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ESS ALPHONSO MANGO', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'BLACK CURRENT CRUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'BLUE CURRACO', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'BLUEBERRIES', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'BLUEBERRY CRUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'BUTTER STOCH CRUSH (0.750 GMS)', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'BUTTER STOCH CRUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'GREEN APPLE CRUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'KIWI CRUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'LICHI CRUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'MANGO CRUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ORANGE CRUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'PINEAPPLE CRUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'STRABERRY  CRUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'VENNILA CRUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'AROMAT MIX', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'Soya Sauce 700 ML', category: 'ESS', uom: 'NOS', suppliers: ['MK SPICES'] },
  { item: 'Chilly Sauce', category: 'ESS', uom: 'NOS', suppliers: ['MK SPICES'] },
  { item: 'Pizza Sauce', category: 'ESS', uom: 'NOS', suppliers: ['MK SPICES'] },
  { item: 'TOMATO KETCHUP (8 GM PKT)', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'TOMATO SAUCE', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'TOMATO KETCHUP', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'Spray Clour Pink', category: 'ESS', uom: 'NOS', suppliers: ['MK SPICES'] },
  { item: 'Spray Clour RED', category: 'ESS', uom: 'NOS', suppliers: ['MK SPICES'] },
  { item: 'SPRAY COLOR GREEN', category: 'ESS', uom: 'NOS', suppliers: ['MK SPICES'] },
  { item: 'Spray Color LEMON YELLOW', category: 'ESS', uom: 'NOS', suppliers: ['MK SPICES'] },
  { item: 'Spray COLOR PURPLE', category: 'ESS', uom: 'NOS', suppliers: ['MK SPICES'] },
  { item: 'SPRAY COLOR BLUE', category: 'ESS', uom: 'NOS', suppliers: ['MK SPICES'] },
  { item: 'SPRAY COLOR SILVER', category: 'ESS', uom: 'NOS', suppliers: ['MK SPICES'] },
  { item: 'CHOCOLATE BUSH', category: 'ESS', uom: 'NOS', suppliers: ['MK SPICES'] },
  { item: 'APPLE GREEN BUSH TIN', category: 'ESS', uom: 'NOS', suppliers: ['MK SPICES'] },
  { item: 'KESARI BUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'LIQ LEMON YELLOW', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'LIQ TOMATO RED', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'LIQ BLUE COLOUR', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'LIQ CHOCLATE BROWN COLOUR', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'LIQ ORANGE RED COLOUR', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'LIQ LODDU COLOUR C', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'LIQ ROSE PINK COLOUR', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'LIQ PISTA GREEN COLOUR', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'LIQ GREEN COLOUR 100 ML', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'LIQ KESHARI B', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'LIQ BLACK CURRENT', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ORANGE & RED BUSH TIN', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'PINEAPPLE BUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'VENNILA BUSH', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'LEMON YELLOW BUSH TIN', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'MTR BADAM MIX 500 gm bottle', category: 'ESS', uom: 'NOS', suppliers: ['mk spices'] },
  { item: 'ROSE WATER', category: 'ESS', uom: 'NOS', suppliers: [] },
  { item: 'LEE KEE KUM LIGHT SOYA SAUCE', category: 'ESS', uom: 'NOS', suppliers: ['NEB'] },
  { item: 'LEE KEE KUM DARK SOYA SAUCE', category: 'ESS', uom: 'NOS', suppliers: ['NEB'] },
  { item: 'CHINESE WINE VINIGAR 640 ML', category: 'ESS', uom: 'NOS', suppliers: ['NEB'] },
  { item: 'OYSTER SAUCE 500 ML LKK', category: 'ESS', uom: 'NOS', suppliers: ['MK SPICES'] },
  { item: 'BREAD KNIFE', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'CAKE BOARD GOLD', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'CAKE PILLER 5 INCH', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'CAKE SLICON DCORATING', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'CAKE TOPPERS SP', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'DECOR PEARL 500 G', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'FANCY STAND 500 GMS (JIMMIES)', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'FOOD GEL COLOUR DARK GREEN', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'FOOD GEL COLOUR ELECTRIC PINK', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'FOOD GEL COLOUR ELECTRIC YELLOW', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'FOOD GEL COLOUR GOLD', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'FOOD GEL COLOUR ORANGE', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'FOOD GEL COLOUR PURBLE', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'FOOD GEL COLOUR ROYAL BLUE', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'FOOD GEL COLOUR SUPER BLACK', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'FOOD GEL COLOUR SUPER RED', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'KABAB STICK 12 THICK', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'LY LIQUID 500', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'NUDRATH JELLY CUBES 1 KG', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'SILICON MOULD BIG', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'SILICON SPATULA', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'WHITE GLAS D 15 SQUARE', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'WINE GLASS 110 ML', category: 'CAKE', uom: 'Nos', suppliers: ['mk spices'] },
  { item: 'BLACH CHEF COAT/ CHED PANT', category: 'UNIFORM & VESSELS', uom: 'NOS', suppliers: [] },
  { item: 'BLACK CHEF COAT/ CHECKED PANT', category: 'UNIFORM & VESSELS', uom: 'NOS', suppliers: [] },
  { item: 'FORMAL PANT BLACK', category: 'UNIFORM & VESSELS', uom: 'NOS', suppliers: [] },
  { item: 'FORMAL SHIRT', category: 'UNIFORM & VESSELS', uom: 'NOS', suppliers: [] },
  { item: 'WHITE CHEF COAT', category: 'UNIFORM & VESSELS', uom: 'NOS', suppliers: [] },
  { item: 'GAS LIGHTER', category: 'UNIFORM & VESSELS', uom: 'NOS', suppliers: ['UNIVERSAL VENDORS'] },
  { item: 'PIZZA CUTTER', category: 'UNIFORM & VESSELS', uom: 'NOS', suppliers: [] },
  { item: 'COTTON CLOTH (KAADA THUNI)', category: 'UNIFORM & VESSELS', uom: 'NOS', suppliers: ['UNIVERSAL VENDORS'] },
];

export interface SupplierMaster {
  name: string;
  itemCount: number;
}

export const SUPPLIER_MASTER: SupplierMaster[] = [
  { name: 'NUTRIA FOODS', itemCount: 2 },
  { name: 'MK SPICES', itemCount: 219 },
  { name: 'KRISHNA ENTERPRISES', itemCount: 1 },
  { name: 'SS PANDIAN & SONS', itemCount: 1 },
  { name: 'NEB', itemCount: 13 },
  { name: 'GEETHA STOTE', itemCount: 1 },
  { name: 'JA VEE YES', itemCount: 7 },
  { name: 'SRI VENKATESHWARA', itemCount: 2 },
  { name: 'SHIVAMANI AGENCIES', itemCount: 2 },
  { name: 'SRINIVASA AGENCIES', itemCount: 3 },
  { name: 'apooji', itemCount: 7 },
  { name: 'PANDIYAN EGGS', itemCount: 1 },
  { name: 'OTHERS', itemCount: 4 },
  { name: 'IYYANGAR BAKEREY', itemCount: 1 },
  { name: 'SSS AGENCY', itemCount: 1 },
  { name: 'SARASWATHY UNPOLISHED GRAINS', itemCount: 1 },
  { name: 'GUNAVATHY COVA', itemCount: 2 },
  { name: 'RAGAVENDRA TRADERS', itemCount: 2 },
  { name: 'JA VEE YES CO', itemCount: 8 },
  { name: 'UNIVERSAL VENDORS', itemCount: 8 },
  { name: 'GUNAVATHY', itemCount: 1 },
  { name: 'DRY FRUIT SHOP BERIGAI', itemCount: 1 },
  { name: 'SRI RAM REDDY', itemCount: 1 },
  { name: 'NEW SURYA HOUSE', itemCount: 1 },
  { name: 'GOLDEN FARIMART', itemCount: 2 },
  { name: 'JA VE SE', itemCount: 2 },
  { name: 'AKSHITHA ENTERPRISES', itemCount: 4 },
  { name: 'DD', itemCount: 1 },
  { name: 'ANEESH', itemCount: 21 },
  { name: 'ANEESH BHAI', itemCount: 14 },
  { name: 'SSR SOLUTIONS', itemCount: 1 },
  { name: 'ANEESH BAY', itemCount: 3 },
  { name: 'ESAA', itemCount: 1 },
  { name: 'SS POLYMERS', itemCount: 2 },
  { name: 'S TEX TRADING', itemCount: 2 },
  { name: 'DD SUPER MARKET', itemCount: 1 },
  { name: 'CKV ENTERPRISES', itemCount: 1 },
  { name: 'GUPTA PRINTERS SIVAKASI', itemCount: 1 },
  { name: 'GUPTA PRINTERS', itemCount: 3 },
  { name: 'NRB AGENCY', itemCount: 2 },
  { name: 'SSS AGENCY WHOLESALE', itemCount: 3 },
  { name: 'SARASWATHY', itemCount: 34 },
  { name: 'JA VEE YAE', itemCount: 9 },
  { name: 'MANJUNATHA MILK', itemCount: 1 },
  { name: 'MILK Dairy', itemCount: 1 },
  { name: 'MILK DIARY', itemCount: 1 },
  { name: 'MURALI MARKET', itemCount: 31 },
  { name: 'MANJU ONION', itemCount: 6 },
  { name: 'KAMATCHI LEAF MUNDY', itemCount: 1 },
  { name: 'SRI KAMATCHICHI', itemCount: 2 },
  { name: 'SK ENTERPRISES', itemCount: 3 },
  { name: 'MYURA', itemCount: 2 },
  { name: 'cool magic agencies', itemCount: 56 },
];

// Map item name -> suppliers for quick lookup
export function getSuppliersForItem(itemName: string): string[] {
  const key = itemName.trim().toUpperCase();
  const found = STORE_ITEM_MASTER.find(x => x.item.toUpperCase() === key);
  return found?.suppliers ?? [];
}

// Fuzzy search items by name
export function searchItems(query: string): StoreItemMaster[] {
  if (!query.trim()) return STORE_ITEM_MASTER.slice(0, 50);
  const q = query.trim().toUpperCase();
  return STORE_ITEM_MASTER.filter(x => x.item.toUpperCase().includes(q)).slice(0, 60);
}

// Get all unique supplier names
export function getAllSupplierNames(): string[] {
  return SUPPLIER_MASTER.map(s => s.name);
}

// Get items for a supplier
export function getItemsForSupplier(supplierName: string): string[] {
  const key = supplierName.trim().toUpperCase();
  return STORE_ITEM_MASTER.filter(x => x.suppliers.some(s => s.toUpperCase() === key)).map(x => x.item);
}
